### PR TITLE
optimise for sdmmc init

### PR DESCRIPTION
**Pull request by guangliangliao**
becase of the hardware 4bits EMMC begin with 8bits SDMMC buswidth will cause some problem,so add bMaxBusWidth to fixed them

### CODE REVIEW

**Comment by TonyHan11** [comment]
Thank you for your pull request. 

Not know if the purpose of f14b407 is to speed up execution, use dedicated bus width or something else? A dedicated data bus width could be used by [adding parameters in sam-ba command](https://github.com/atmelcorp/sam-ba/blob/v3.3.1/doc/sdmmc.qdoc#L19). 

For d458bd0, the [bus width of MT47H128M16](https://github.com/atmelcorp/atmel-software-package/pull/98/commits/d458bd0011723fe6fc65cef6e83f2d192e50e505#diff-36120ec419acae41f016fcff3ba93af0R1090) should be kept as previous 32, and [the preset for MT47H128M16](https://github.com/atmelcorp/atmel-software-package/pull/98/commits/d458bd0011723fe6fc65cef6e83f2d192e50e505#diff-521a5b599d983963d21f0ca5c54229cbR90) should also be kept as 2, otherwise the examples/applets using DDR MT47H128M16 would fail.

In softpack each commit usually contains files in the same directory. The better commit message here might be: "drivers/extram: add support for dual MT47H128M16" and "samba_applets/extram: update to support dual MT47H128M16". In the commit message you'd better add the "Signed-off-by: " with your e-mail address.

**Comment by guangliangliao** [comment]
Hello,
  1、 For f14b407 this commit,I had been set QML config sdmmc busWidth:4, if hardware is 4bits eMMC, would cause /lib/libsdmmc/sdmmc_api.c:mmcDetectBuswidth  deep sleep and not return yet if you not beigin with 4bits buswidth!
  2、For d458bd0, this commit is resvered for SAMA5D4 16bits single DDR, set preset as 18 .
  3、For your commit suggestion,I will pay attention to it next commit,Thanks !

**Comment by TonyHan11** [comment]
No know if you are updating the commits for this PR, if you don't mind, I'd like to rework them later.

**Comment by TonyHan11** [comment]
Commits merged to the master branch, close this PR.
[lib/libsdmmc: support detecting the bus width of MMC from dedicated width](https://github.com/atmelcorp/atmel-software-package/commit/145c6e5ec5840b5a4227e14c25e4245281e0c792)
[samba_applets/sdmmc: support detecting the bus width of MMC from dedicated width](https://github.com/atmelcorp/atmel-software-package/commit/c6a2899ef1bc6176f8f8f83d73b08202483d9885)
[drivers/extram: add support for single DDR2 MT47H128M16](https://github.com/atmelcorp/atmel-software-package/commit/82a86b40320d91792f85f39e73a26daeb815165b)
[samba_applets/extram: add support for single DDR2 MT47H128M16](https://github.com/atmelcorp/atmel-software-package/commit/45d558f263815618703464b26b0f087bc2d9d64c)

**Pull request closed without merging**
