### PR TITLE
Fix PIN_UART3_RXD_IOS2 definition

### PR DESCRIPTION
**Pull request by Eurecam-Benjamin**
just as written in title, a small typo in PIN_UART3_RXD_IOS2 definition

### CODE REVIEW

**Comment by TonyHan11** [comment]
Hi,
Thank you for your pull request. You are right, the PIO group of `PIN_UART3_RXD_IOS2` should be `PIO_GROUP_C`.
Would you like to update the commit message to "`target/sama5d2: fix PIN_UART3_RXD_IOS2 definition`" and add `Signed-off-by: ` with your name and e-mail address? Thanks.

**Comment by Eurecam-Benjamin** [comment]
Yes for sure, no problem.
You're welcome.

**Comment by TonyHan11** [comment]
Thank you for the commit ([117c3bc](https://github.com/atmelcorp/atmel-software-package/pull/118/commits/117c3bcaf08def0cb8682c99a94520636cec9dcd)) on the phy driver. Would you like to update the commit message to `"drivers/network: fix errors in phy driver"` and add `Signed-off-by:` with your name and e-mail address?
As the commits only be merged in the `fast-forward` way, would you rebase your commits on the latest master branch, Thanks.

**Comment by TonyHan11** [comment]
Re-based and merged the commits to the master branch (commit message updated), thank you.

**Pull request merged**
